<?php

/**
 * This is the model base class for the table "user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "user" available as properties of the model,
 * followed by relations of table "user" available as properties of the model.
 *
 * @property integer $id
 * @property integer $group
 * @property integer $status
 * @property string $username
 * @property string $password
 * @property string $firstname
 * @property string $lastname
 * @property integer $idposition
 * @property string $salt
 *
 * @property Position $idposition0
 * @property UserRequests[] $userRequests
 */
abstract class BaseUser extends GxActiveRecord {
    public $old_password;
    public $new_password;
    public $repeat_password;

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'User|Users', $n);
	}

	public static function representingColumn() {
		return 'username';
	}

	public function rules() {
		return array(
			array('group, status, username, password, firstname, lastname, idposition, salt', 'required'),
			array('group, status, idposition', 'numerical', 'integerOnly'=>true),
			array('username, firstname, lastname', 'length', 'max'=>20),
			array('password, salt', 'length', 'max'=>32),
			array('id, group, status, username, password, firstname, lastname, idposition, salt', 'safe', 'on'=>'search'),

			array('old_password, new_password, repeat_password', 'required', 'on' => 'changePwd'),
	        array('old_password', 'findPasswords', 'on' => 'changePwd'),
	        array('repeat_password', 'compare', 'compareAttribute'=>'new_password', 'on'=>'changePwd'),
		);
	}

	public function relations() {
		return array(
			'idposition0' => array(self::BELONGS_TO, 'Position', 'idposition'),
			'userRequests' => array(self::HAS_MANY, 'UserRequests', 'iduser'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'group' => Yii::t('app', 'Group'),
			'status' => Yii::t('app', 'Status'),
			'username' => Yii::t('app', 'Username'),
			'password' => Yii::t('app', 'Password'),
			'firstname' => Yii::t('app', 'Firstname'),
			'lastname' => Yii::t('app', 'Lastname'),
			'idposition' => null,
			'salt' => Yii::t('app', 'Salt'),
			'idposition0' => null,
			'userRequests' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
       if(isset($_GET['p'])){

        	 $criteria->addCondition('id='.Yii::app()->user->id);
        }
		$criteria->compare('id', $this->id);
		$criteria->compare('group', $this->group);
		$criteria->compare('status', $this->status);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('firstname', $this->firstname, true);
		$criteria->compare('lastname', $this->lastname, true);
		$criteria->compare('idposition', $this->idposition);
		$criteria->compare('salt', $this->salt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}



	// hash password
public function hashPassword($password, $salt)
{
    return md5($salt.$password);
}
        
// password validation
public function validatePassword($password)
{
    return $this->hashPassword($password,$this->salt)===$this->password;
}
        
//generate salt
public function generateSalt()
{
    return uniqid('',true);
}
        
public function beforeValidate()
{
    $this->salt = $this->generateSalt();
    return parent::beforeValidate();
}
        
public function beforeSave()
{
    $this->password = $this->hashPassword($this->password, $this->salt);
    return parent::beforeSave();
}

 public function findPasswords($attribute, $params)
    {
        $user = User::model()->findByPk(Yii::app()->user->id);
        if ($user->password != md5($user->salt.$this->old_password))
            $this->addError($attribute, 'Old password is incorrect.');
    }

 public function Passwords()
    {
        $user = User::model()->findByPk(Yii::app()->user->id);
        $newpassword=md5($user->salt.$this->new_password);
        //return "coco";
    }

    static function getGroups($k){

	if($k == 2)
		 return "Admin";
    else if($k == 1)
    	return 'Administrative';
    	
    else
    	return 'Receptionist';

}

}