<?php

/**
 * This is the model base class for the table "response".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Response".
 *
 * Columns in table "response" available as properties of the model,
 * followed by relations of table "response" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idrequest
 * @property string $response
 * @property string $response_date
 *
 * @property Request $idrequest0
 */
abstract class BaseResponse extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'response';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Response|Responses', $n);
	}

	public static function representingColumn() {
		return 'response';
	}

	public function rules() {
		return array(
			array('idrequest, response, response_date', 'required'),
			array('idrequest', 'numerical', 'integerOnly'=>true),
			array('id, idrequest, response, response_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idrequest0' => array(self::BELONGS_TO, 'Request', 'idrequest'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idrequest' => null,
			'response' => Yii::t('app', 'Response'),
			'response_date' => Yii::t('app', 'Response Date'),
			'idrequest0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idrequest', $this->idrequest);
		$criteria->compare('response', $this->response, true);
		$criteria->compare('response_date', $this->response_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}