<?php

/**
 * This is the model base class for the table "departments".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Departments".
 *
 * Columns in table "departments" available as properties of the model,
 * followed by relations of table "departments" available as properties of the model.
 *
 * @property integer $id
 * @property string $department
 *
 * @property Position[] $positions
 */
abstract class BaseDepartments extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'departments';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Departments|Departments', $n);
	}

	public static function representingColumn() {
		return 'department';
	}

	public function rules() {
		return array(
			array('department', 'required'),
			array('department', 'length', 'max'=>50),
			array('id, department', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'positions' => array(self::HAS_MANY, 'Position', 'iddepertment'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'department' => Yii::t('app', 'Department'),
			'positions' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('department', $this->department, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}