<?php

/**
 * This is the model base class for the table "Position".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Position".
 *
 * Columns in table "Position" available as properties of the model,
 * followed by relations of table "Position" available as properties of the model.
 *
 * @property integer $id
 * @property integer $iddepertment
 * @property string $jobTitle
 *
 * @property Departments $iddepertment0
 * @property User[] $users
 */
abstract class BasePosition extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Position';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Position|Positions', $n);
	}

	public static function representingColumn() {
		return 'jobTitle';
	}

	public function rules() {
		return array(
			array('iddepertment, jobTitle', 'required'),
			array('iddepertment', 'numerical', 'integerOnly'=>true),
			array('jobTitle', 'length', 'max'=>100),
			array('id, iddepertment, jobTitle', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'iddepertment0' => array(self::BELONGS_TO, 'Departments', 'iddepertment'),
			'users' => array(self::HAS_MANY, 'User', 'idposition'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'iddepertment' => null,
			'jobTitle' => Yii::t('app', 'Job Title'),
			'iddepertment0' => null,
			'users' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('iddepertment', $this->iddepertment);
		$criteria->compare('jobTitle', $this->jobTitle, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}